site_description: "Vue.js - O Framework JavaScript Progressivo"
google_analytics: UA-46852172-1
<<<<<<< HEAD
root_domain: br.vuejs.org
vue_version: 2.4.0
=======
root_domain: vuejs.org
vue_version: 2.4.4
>>>>>>> 68515d282f73b52ed8c51ba775eba227cd7cfd49
